<a href="https://colab.research.google.com/github/joaohnt/estudo_ml/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 12.7 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

# base salario idade

In [3]:
from sklearn.cluster import KMeans

In [5]:
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [7]:
grafico = px.scatter(x = x, y = y)
grafico.show()

In [8]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

In [9]:
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [11]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [12]:
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [13]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [14]:
centroides = kmeans_salario.cluster_centers_
centroides

array([[ 0.73953003, -0.72661025],
       [-1.63312883, -0.77505093],
       [ 0.07703438,  1.11413572]])

In [17]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[ 0.73953003, -0.72661025],
       [-1.63312883, -0.77505093],
       [ 0.07703438,  1.11413572]])

In [22]:
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=kmeans_salario.labels_)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [12,12,12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

# dados randomicos

In [23]:
from sklearn.datasets import make_blobs

In [31]:
X_random, y_random = make_blobs(n_samples = 200, centers = 5)

In [29]:
X_random[0:10]

array([[ 3.33827185, -6.64293722],
       [-2.75166956,  3.64805798],
       [ 4.04237241, -7.19661454],
       [ 3.36433879, -7.8607811 ],
       [-2.5275972 ,  4.51681084],
       [-6.05890918,  0.65336899],
       [ 3.95476216, -5.19236879],
       [ 3.40924564, -5.31366633],
       [ 2.75728267, -5.03015323],
       [ 2.7393671 , -7.81913627]])

In [26]:
y_random

array([4, 2, 4, 4, 2, 0, 1, 1, 1, 4, 2, 2, 0, 0, 3, 3, 4, 0, 0, 4, 2, 3,
       2, 1, 2, 1, 3, 0, 1, 1, 1, 4, 4, 1, 4, 1, 1, 0, 1, 0, 3, 0, 1, 2,
       3, 1, 0, 0, 2, 2, 3, 4, 1, 1, 0, 3, 2, 4, 2, 2, 4, 0, 4, 3, 0, 0,
       3, 3, 0, 4, 3, 1, 4, 4, 2, 0, 2, 0, 1, 4, 2, 3, 4, 3, 3, 3, 3, 3,
       3, 2, 2, 4, 2, 1, 0, 3, 2, 4, 0, 0, 0, 1, 4, 0, 3, 0, 2, 0, 0, 4,
       3, 3, 2, 0, 0, 4, 4, 2, 4, 4, 0, 1, 1, 1, 1, 2, 3, 0, 2, 3, 4, 2,
       3, 2, 0, 4, 3, 1, 3, 3, 1, 1, 4, 1, 1, 1, 2, 4, 2, 0, 1, 2, 3, 3,
       0, 1, 4, 3, 1, 4, 3, 3, 4, 0, 1, 0, 4, 3, 4, 3, 1, 4, 2, 1, 4, 1,
       2, 2, 3, 0, 2, 1, 2, 3, 2, 4, 4, 2, 3, 1, 0, 0, 2, 3, 1, 2, 0, 0,
       2, 4])

In [32]:
grafico = px.scatter(x = X_random[:,0], y = X_random[:,1])
grafico.show()

In [33]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(n_clusters=5)

In [34]:
rotulos = kmeans_blobs.predict(X_random)
rotulos

array([4, 1, 4, 4, 1, 2, 0, 2, 3, 2, 4, 2, 0, 0, 0, 2, 1, 2, 3, 4, 0, 2,
       0, 4, 3, 0, 1, 3, 0, 3, 2, 4, 1, 0, 0, 1, 0, 3, 4, 3, 2, 1, 0, 4,
       1, 4, 3, 3, 4, 3, 4, 3, 4, 3, 0, 2, 4, 2, 3, 0, 2, 4, 4, 4, 1, 2,
       1, 0, 2, 0, 2, 0, 4, 4, 4, 1, 0, 4, 0, 0, 0, 1, 2, 4, 0, 2, 3, 2,
       1, 3, 4, 2, 3, 4, 4, 1, 1, 1, 4, 1, 0, 0, 1, 0, 3, 4, 2, 2, 0, 1,
       2, 3, 2, 0, 0, 0, 1, 3, 1, 0, 0, 4, 3, 2, 0, 4, 3, 2, 0, 2, 1, 3,
       1, 4, 2, 1, 1, 4, 3, 1, 1, 3, 4, 2, 2, 1, 1, 3, 1, 1, 1, 4, 2, 4,
       1, 3, 2, 1, 2, 1, 0, 3, 3, 2, 0, 0, 3, 2, 1, 0, 1, 0, 2, 3, 1, 2,
       4, 2, 0, 3, 0, 4, 2, 3, 3, 2, 3, 4, 3, 0, 0, 3, 3, 0, 1, 3, 3, 1,
       3, 2], dtype=int32)

In [35]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[ 8.15744455, -3.38516535],
       [-9.50638591,  4.98703911],
       [-1.90020656, -3.74923554],
       [ 4.27597075, -8.17881326],
       [10.28316843, -3.04824478]])

In [42]:
grafico1 = px.scatter(x = X_random[:,0], y = X_random[:,1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [5,5,5,5,5])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

# base cartao de credito

In [43]:
import pandas as pd
base_cartao = pd.read_csv('/content/credit_card_clients.csv', header = 1)
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [44]:
base_cartao['BILL_TOTAL'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5'] + base_cartao['BILL_AMT6']

In [45]:
base_cartao

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0         -1  ...          0          0         0       689         0   
1          0  ...       3455       3261         0      1000      1000   
2          0  ...      14948      15549      1518      1500      1000   
3          0  ...      28959      29547      2000      2019      1200   
4          0  ...      19146      19131      2000     36681     10000   
...      ...  ...        ...        ...       ...       ...       ...   
29995      0  ...      31237      15980      8500     20000      5003   
29996     -1  ...       5190          0      1837      3526      8998   
29997     -1  ...      20582      19357         0         0     22000   
29998      0  ...      11855      48944     85900      3409      1178   
29999      0  ...      32428      15313      2078      1800      1430   

       PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  BILL_TOTAL  
0             0         0         0                           1        7704  
1          1000         0      2000                           1       17077  
2          1000      1000      5000                           0      101653  
3          1100      1069      1000                           0      231334  
4          9000       689       679                           0      109339  
...         ...       ...       ...                         ...         ...  
29995      3047      5000      1000                           0      725349  
29996       129         0         0                           0       21182  
29997      4200      2000      3100                           1       70496  
29998      1926     52964      1804                           1      266611  
29999      1000      1000      1000                           1      230874  

[30000 rows x 26 columns]

In [47]:
X_cartao = base_cartao.iloc[:, [1,25]].values
X_cartao

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]])

In [48]:
scaler_cartao = StandardScaler()
X_cartao = scaler_cartao.fit_transform(X_cartao)

In [49]:
X_cartao

array([[-1.13672015, -0.69069198],
       [-0.3659805 , -0.66599747],
       [-0.59720239, -0.44316987],
       ...,
       [-1.05964618, -0.52525745],
       [-0.67427636, -0.00856436],
       [-0.90549825, -0.10271861]])

In [52]:
wcss = []
for i in range(1, 11):
  kmeans_cartao = KMeans(n_clusters=i, random_state = 0)
  kmeans_cartao.fit(X_cartao)
  wcss.append(kmeans_cartao.inertia_)

In [53]:
wcss

[59999.99999999962,
 35197.83439125732,
 20128.20263562325,
 15892.249716910846,
 10708.603774943429,
 8604.404544864514,
 7684.904846136829,
 6593.001391781384,
 5669.721586002757,
 5055.083531903275]

In [54]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [64]:
kmeans_cartao = KMeans(n_clusters = 4, random_state = 0)
rotulos = kmeans_cartao.fit_predict(X_cartao)

In [65]:
grafico = px.scatter(x = X_cartao[:,0], y = X_cartao[:,1], color = rotulos)
grafico.show()

In [67]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  17077,      0],
       [     3,  90000,      2, ...,      0, 101653,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  70496,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 30000,  50000,      1, ...,      1, 230874,      0]])

In [69]:
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [ 22742,  80000,      2, ...,      0, 330716,      0],
       [ 22736,  60000,      2, ...,      0,  76973,      0],
       ...,
       [ 27952, 280000,      2, ...,      0,      0,      3],
       [   931, 260000,      2, ...,      0, 339021,      3],
       [ 19905, 210000,      2, ...,      0,   4580,      3]])

usando + atributos

In [70]:
base_cartao.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'BILL_TOTAL'],
      dtype='object')

In [71]:
X_cartao_mais = base_cartao.iloc[:,[1,2,3,4,5,25]].values
X_cartao_mais

array([[ 20000,      2,      2,      1,     24,   7704],
       [120000,      2,      2,      2,     26,  17077],
       [ 90000,      2,      2,      2,     34, 101653],
       ...,
       [ 30000,      1,      2,      2,     37,  70496],
       [ 80000,      1,      3,      1,     41, 266611],
       [ 50000,      1,      2,      1,     46, 230874]])

In [72]:
scaler_cartao_mais = StandardScaler()
X_cartao_mais = scaler_cartao_mais.fit_transform(X_cartao_mais)

In [73]:
X_cartao_mais

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -1.24601985,
        -0.69069198],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -1.02904717,
        -0.66599747],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.16115646,
        -0.44316987],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728,  0.16430256,
        -0.52525745],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503,  0.59824792,
        -0.00856436],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503,  1.14067961,
        -0.10271861]])

In [77]:
wcss = []
for i in range(1, 11):
  kmeans_cartao_mais = KMeans(n_clusters=i, random_state = 0)
  kmeans_cartao_mais.fit(X_cartao_mais)
  wcss.append(kmeans_cartao_mais.inertia_)

In [78]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [91]:
kemans_cartao_mais = KMeans(n_clusters=2, random_state=0)
rotulos = kmeans_cartao_mais.fit_predict(X_cartao_mais)

In [92]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_cartao_mais_pca = pca.fit_transform(X_cartao_mais)

In [93]:
X_cartao_mais_pca.shape

(30000, 2)

In [94]:
grafico = px.scatter(x = X_cartao_mais_pca[:,0], y = X_cartao_mais_pca[:,1], color = rotulos)
grafico.show()